### ISSUE TITLE
Working with addresses (create, balance)

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core#10]
Why: exporting and importing wallet is the first and the most basic part of wallet functionality.
What: user should be able import or export wallet throught private key and mnemonic

https://github.com/elastos/Elastos.ORG.Wallet.Lib.C

**Comment by andersalm** [comment]
Followed up [here](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/9) and [here](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/8)
