### ISSUE TITLE
Import/export wallet (private key, mnemonic)

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core#5]
Why: exporting and importing wallet is the first and the most basic part of wallet functionality.
What: user should be able import or export wallet throught private key and mnemonic

https://github.com/elastos/Elastos.ORG.Wallet.Lib.Android

**Comment by andersalm** [comment]
@EricDualc did you get this resolved? is this done?

**Comment by EricDualc** [comment]
importwallet was done on my new commit - "add new bridges for alpha"
But exportwallet wan't done but it isn't needed for the alpha.
We are focusing on alpha so I'm going to do it later.
