### ISSUE TITLE
Wallet balance

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core#8]
Why: wallet balance is the most basic part of wallet functionality.
What: user should be able to find out the balance of wallet

https://github.com/elastos/Elastos.ORG.Wallet.Lib.C

Estimated time left: 8 hours

**Comment by ademcan** [comment]
Implemented in https://github.com/cyber-republic/react-native-elastos-wallet-core/pull/22
