### ISSUE TITLE
Import/export wallet (private key, mnemonic)

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core#9]
Why: exporting and importing wallet is the first and the most basic part of wallet functionality.
What: user should be able import or export wallet throught private key and mnemonic

https://github.com/elastos/Elastos.ORG.Wallet.Lib.C

Estimated time left: 8 hours

**Comment by ademcan** [comment]
Implemented in https://github.com/cyber-republic/react-native-elastos-wallet-core/pull/22 (except for export)
